baseURL = 'https://Psylar87.github.io'
languageCode = 'en-us'
title = 'Byte Blog'
theme = "hugo-theme-m10c"

[params]
  contentTypeName = "post"
  author = "Brandon Card"
  avatar = "/avatar.png"
  description = "Hello, I’m Brandon Card. As a newcomer to the coding world, I’m dedicated to learning and becoming better every day. Follow along as I document my progress and share my discoveries."
  menu_item_separator = " - "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/psylar87"
